### PR TITLE
added invalid_email attribute

### PR DESCRIPTION
**Pull request by mcnesium**
got another one :)

### CODE REVIEW

**Comment by cubiq** [comment]
can't merge, are you using the same version that is online?

**Comment by mcnesium** [comment]
I was messing around with git branches, since I failed to set the pull request before I did other changes.

In [my fork](https://github.com/mcnesium/wp-frontend-login) I changed the template files, so that the form distinction is done by php rather than the js-tabs. So I dont want to set all that as pull request, since it is actually a real fork of your work.

So I don't really know how to solve this thing here now. You can just copy those two lines in your login.php by yourself I guess, and I go ahead and delete the extra branch.

**Comment by cubiq** [comment]
I will. Thanks!

**Comment by cubiq** [comment]
done. I've also removed a redundant `if`

**Pull request closed without merging**
